language: node_js
node_js:
  - "10"
before_script:
  - npx version-from-git --travis --no-git-tag-version
  - npm run bootstrap
  - node scripts/syncVersion
  - npm run build
before_deploy:
  - cp -r packages/component/lib .
deploy:
  - provider: npm
    api_key:
      secure: "KVUw0TlDtiQ5M5NtCA0f5NvZtTFI7oF50p8K324K8KkrQc/E6r169+gX2A/K1A2YlCKz5wjPQx4i6C05+zBuhxoVHxxiXnEmciXe4QNZX5F7dW5O7LKCpiGtB8H+UwHUnZOTtdJxhsjKYKhIBlZR9cr6Kiye7bFKLP+AQUZTBNVr3gWLe9dsyZdwjsIr5xQaHqoYJxGebD4a7ssPYJCEuKuGykwkz/T7DVuJq5IZAIvLV0Wib2Di1kBzGUjh8ka3KKfN3OQicsSMU0+Rpws/MjkGa89KJhSbe37jG+dYPD428Ap6DbqDT2KIzRQXjhGf9mHSyDzUSsia4zJVfQmylPpYlrul9dhsLfjJltQHNYnKbQoRyYRrqFizhsJtx/+F7SwZ07vFxY/DzRmfuCD2sFUlbcY2hmDHdtLz0/JRF9qZUIwf1U7dUEOu+4Qyfho0hsJJurQ9kw9A1Nl2MVjWH++94YT0RfceW60lqUfSUXuEHhME9utgcZ4Kke3tIHarPWw6g9mf0T0NRYVR4DdAYXQ+Yl1BqsyYU/NmtdW7fMl1dyzqe9dIhTd4S4g/OUb0lKYwjdPQGrAPyTn23vnNxRHgGsayAPQC72Oe3QdRXdDfT7+InTVExEuor8hgD7NmFb1zMUiiQurud+UjVVsbqvSLHAzYaEENq4jGNWMMV04="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "KVUw0TlDtiQ5M5NtCA0f5NvZtTFI7oF50p8K324K8KkrQc/E6r169+gX2A/K1A2YlCKz5wjPQx4i6C05+zBuhxoVHxxiXnEmciXe4QNZX5F7dW5O7LKCpiGtB8H+UwHUnZOTtdJxhsjKYKhIBlZR9cr6Kiye7bFKLP+AQUZTBNVr3gWLe9dsyZdwjsIr5xQaHqoYJxGebD4a7ssPYJCEuKuGykwkz/T7DVuJq5IZAIvLV0Wib2Di1kBzGUjh8ka3KKfN3OQicsSMU0+Rpws/MjkGa89KJhSbe37jG+dYPD428Ap6DbqDT2KIzRQXjhGf9mHSyDzUSsia4zJVfQmylPpYlrul9dhsLfjJltQHNYnKbQoRyYRrqFizhsJtx/+F7SwZ07vFxY/DzRmfuCD2sFUlbcY2hmDHdtLz0/JRF9qZUIwf1U7dUEOu+4Qyfho0hsJJurQ9kw9A1Nl2MVjWH++94YT0RfceW60lqUfSUXuEHhME9utgcZ4Kke3tIHarPWw6g9mf0T0NRYVR4DdAYXQ+Yl1BqsyYU/NmtdW7fMl1dyzqe9dIhTd4S4g/OUb0lKYwjdPQGrAPyTn23vnNxRHgGsayAPQC72Oe3QdRXdDfT7+InTVExEuor8hgD7NmFb1zMUiiQurud+UjVVsbqvSLHAzYaEENq4jGNWMMV04="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: "l0NLN6VxUID9rbxl9CCvNAStsFxYR1dZpEGK++YieJi7VNdCMzr69vU4jaK+6B2WVGKBE6w4Df/6ssgHjGTyE8egS1XM/4JtPyP6jJfhuHAaZgs3VLEGPpLC/nmdEDYJ93APnKSNCKsqiVKvwleu9/ZRLXsHVnBpKkNpEdU7kNN2Iq9SsnHyttbP3KcN10OT8icr4sVe6LXtsZ3RHyxxk+keBt2Q1ipi7EPxwu9V/a+eW4A2XDGXV1ttwbbrDuV4Gy8N277mWuniWMJLDBD4BNFNQPzwaSl/grA8x/S+WzmM+u4U3ux7YpaywYlbKw0GZgjCMYxTkJ1FlI0V28BABtD/UOL7iTbW0b4GmSlIXn9dVGgkxE6BGuWMjDvc+DzaI8NmCAhfx7ZDp1hIgmOfBm3KkO8Hp0w1UH2NyuaZ4qFZxa0bGGtPiulsclS1JyFHP/CzB7XdX5KpIvyoD9qzTNqf7mabbXipFS3sscuHJD14WKh/jxAgk72e19+T23vtIziLFVFHt4zPeRLeigY2M6/eHZET7mSPkcksvxGLwyxjgmUEHhp+Pu7i4UcKDx/VZ2VTtDRRj9NXO0ZwnxkUSBA6VZ2rtViUU+7ohZVbNTEy5mJDxlbzPjihhvbIZVaMUlrjQ3davS6qSYTGQlHlWfMD6Cy/LmNrvuNJNsUXGMI="
    on:
      branch: master
    local-dir: packages/playground/build
  - provider: releases
    api_key:
      secure: "l0NLN6VxUID9rbxl9CCvNAStsFxYR1dZpEGK++YieJi7VNdCMzr69vU4jaK+6B2WVGKBE6w4Df/6ssgHjGTyE8egS1XM/4JtPyP6jJfhuHAaZgs3VLEGPpLC/nmdEDYJ93APnKSNCKsqiVKvwleu9/ZRLXsHVnBpKkNpEdU7kNN2Iq9SsnHyttbP3KcN10OT8icr4sVe6LXtsZ3RHyxxk+keBt2Q1ipi7EPxwu9V/a+eW4A2XDGXV1ttwbbrDuV4Gy8N277mWuniWMJLDBD4BNFNQPzwaSl/grA8x/S+WzmM+u4U3ux7YpaywYlbKw0GZgjCMYxTkJ1FlI0V28BABtD/UOL7iTbW0b4GmSlIXn9dVGgkxE6BGuWMjDvc+DzaI8NmCAhfx7ZDp1hIgmOfBm3KkO8Hp0w1UH2NyuaZ4qFZxa0bGGtPiulsclS1JyFHP/CzB7XdX5KpIvyoD9qzTNqf7mabbXipFS3sscuHJD14WKh/jxAgk72e19+T23vtIziLFVFHt4zPeRLeigY2M6/eHZET7mSPkcksvxGLwyxjgmUEHhp+Pu7i4UcKDx/VZ2VTtDRRj9NXO0ZwnxkUSBA6VZ2rtViUU+7ohZVbNTEy5mJDxlbzPjihhvbIZVaMUlrjQ3davS6qSYTGQlHlWfMD6Cy/LmNrvuNJNsUXGMI="
    on:
      tags: true
    skip_cleanup: true
