language: node_js
node_js:
  - "10"
before_script:
  - npm run build
before_deploy:
  - npx version-from-git --travis
deploy:
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: ""
    on:
      branch: master
    local-dir: packages/playground/build
